version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/.github"
  schedule:
    interval: "weekly"

- package-ecosystem: "docker"
  directory: "/images/silverblue-nvidia"
  schedule:
    interval: "weekly"
