FROM ghcr.io/ublue-os/silverblue-nvidia:39
COPY root /
RUN rpm-ostree install \
      btrbk strace wireshark \
      terminator zsh make ripgrep \
      code docker golang pipenv && \
    ostree container commit
